name: fl2_qwerty_messenger
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.17.3 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter:
    sdk: flutter
  provider: ^6.0.5



dev_dependencies:
  blackfoot_flutter_lint: ^1.0.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true