name: fl2_qwerty_messenger
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  http: ^0.13.5

  image_picker: ^0.8.6
  provider: ^6.0.5



dev_dependencies:
  blackfoot_flutter_lint: ^1.0.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/